name: LAPRAS Card

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 0 * * *

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: Hanaasagi/lapras-card-readme@main
        with:
          SHARE_ID: 3KR7WDA
          ICON_FIRST: "#212121"
          ICON_SECOND: "#818181"
          BACKGROUND_FIRST: "#232323"
          BACKGROUND_SECOND: "#6d6d6d"
          LANG: "en"
          CARD_WIDTH: "40%"
          UPDATE_TIME: "false"
